openapi: 3.0.0
info:
  title: "vertx-bug"
  version: 3.0.0
paths:

  /:
    get:
      operationId: getRequest
      x-vertx-event-bus: vertx-bug-Bug
      description: >+
      summary: >+
      tags:
        - Bug
      responses:
        '200':
          description: >+
          content:
            application/json; charset=utf-8:
              schema:
                type: object
    patch:
      operationId: patchRequest
      x-vertx-event-bus: vertx-bug-Bug
      description: >+
      summary: >+
      tags:
        - Bug
      requestBody:
        description: >+
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: >+
          content:
            application/json; charset=utf-8:
              schema:
                type: object
